### ISSUE TITLE
Find new home page image

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-codergirlz#11]
Per the convo we had in slack:

Hi Alex; I have a couple of silly questions. Just got the email about Codergirlz- glad they liked it! Only... I'm not sure what they mean by more "modern" pictures... I mean they're pictures of Mac Books with filters on them. The only thing that would make those photos more modern would be if I photoshopped in more Apple products and replaced the tea with a Red Bull. Can I get a little guidance there? Also, should I go ahead and send in an invoice for this project? You said it'd be a separate invoice and I was waiting for the go-ahead.

aleeex [6:17 PM] 
ah so i just read the email

aleeex [6:17 PM]
im 95% sure that what they mean by modern is to have a color pic of some girls around computers

aleeex [6:22 PM]
unfortunately no one there probably knows who margaret hamilton is and understands the significance of that photo

aleeex [6:22 PM]
: |

vanderbeam [7:16 PM] 
Ohhh I see. You know I thought they were focused on the two images lower down didn't even think about the header. OK. I'll look for something a bit more modern, but I may stick to black and white because when I used a colour picture originally it didn't look very good.

aleeex [7:17 PM] 
*nods

aleeex [7:17 PM]
find a color one as well as a backup please

due:
10-18-15  9p

**Comment by vanderbeam** [comment]
I've been to a ton of different [free] stock photo sites and there's not really an abundance of computer pictures that have [girl] kids in them. Here's what I have so far:

![3](https://cloud.githubusercontent.com/assets/12962001/10595483/85fa7bbe-768d-11e5-9b62-bf5c801b3548.png)
![1](https://cloud.githubusercontent.com/assets/12962001/10595484/85fc03bc-768d-11e5-99db-77fd2d057a47.png)
![2](https://cloud.githubusercontent.com/assets/12962001/10595485/85fd3c3c-768d-11e5-8a13-7b8ba33d0222.png)
![4](https://cloud.githubusercontent.com/assets/12962001/10595518/fdeb4784-768d-11e5-972c-3b9019efe3b1.png)

**Comment by vanderbeam** [comment]
Macs. Macs everywhere.

**Comment by irms** [comment]
@aleeex, please share our depositphotos account with @vanderbeam for this
project.

**Comment by rodneystrong** [comment]
@irms good call, just shared them

**Comment by rodneystrong** [comment]
@vanderbeam   i have to advise you, you may find a majority of the photos you find 'unusable' in the sense that the models are a little too old or fake or in unnatural positions. i did a quick search for 'girls programming' and didn't get great results. 

i leave it to your judgement.

**Comment by vanderbeam** [comment]
@rodneystrong Thanks, Alex! And yeah, that's pretty much been my experience in this whole thing. I'll check it out.

**Comment by vanderbeam** [comment]
I think I've found "the one!" 
![10](https://cloud.githubusercontent.com/assets/12962001/10656690/6042f702-7836-11e5-9ddf-5fbaf8cde3b1.png)
http://depositphotos.com/72758835/stock-photo-website-wireframe-sketch-and-programming.html

**Comment by vanderbeam** [comment]
These are some others that I had in mind:
http://depositphotos.com/44126643/stock-illustration-web-coding-and-programming-flat.html
http://depositphotos.com/57454061/stock-illustration-programming-and-coding-website-deveopment.html
http://depositphotos.com/3802588/stock-photo-computer-program-code.html
http://depositphotos.com/35476563/stock-photo-codecss-script-in-text-editor.html
http://depositphotos.com/4755399/stock-photo-female-college-students-in-a.html
http://depositphotos.com/24049059/stock-illustration-internet-doodle.html
http://depositphotos.com/22064167/stock-photo-student-working-on-laptop.html?qview=22064167

Everything else is just tons of variants of female hands on keyboards.

**Comment by rodneystrong** [comment]
sorry, but the theme of that hero image is already replicated in the image you have below it (computers, notes, code). 
This one that you found is really good. 
http://depositphotos.com/4755399/stock-photo-female-college-students-in-a.html
![depositphotos_4755399-female-college-students-in-a-computer-lab](https://cloud.githubusercontent.com/assets/539962/10657675/0c70648a-7844-11e5-8ec6-7540fea040df.jpg)

Some others:
http://depositphotos.com/6818770/stock-photo-college-student-on-cafe.html
![depositphotos_6818770-college-student-on-cafe](https://cloud.githubusercontent.com/assets/539962/10657692/2d7eebba-7844-11e5-8ed7-22e50f667d0c.jpg)

http://depositphotos.com/21973119/stock-photo-female-student-with-classmates-in.html
![depositphotos_21973119-female-student-with-classmates-in-computer-laboratory](https://cloud.githubusercontent.com/assets/539962/10657698/3c9d141e-7844-11e5-83dd-1379871dcbad.jpg)

http://depositphotos.com/77278864/stock-photo-web-page-code-html.html
![depositphotos_77278864-web-page-code-html](https://cloud.githubusercontent.com/assets/539962/10657706/48dfeb84-7844-11e5-848a-cc653bc99c59.jpg)

http://depositphotos.com/77305210/stock-photo-smiling-woman-working-in-office.html
![depositphotos_77305210-smiling-woman-working-in-office](https://cloud.githubusercontent.com/assets/539962/10657708/59660560-7844-11e5-97ff-915e45a324d8.jpg)

http://depositphotos.com/61562765/stock-photo-scientist-develops-software.html
![depositphotos_61562765-scientist-develops-software](https://cloud.githubusercontent.com/assets/539962/10657718/6b3939ce-7844-11e5-9089-da7b87d36859.jpg)

http://depositphotos.com/68852739/stock-photo-data-stream.html
![depositphotos_68852739-data-stream](https://cloud.githubusercontent.com/assets/539962/10657748/d84182f6-7844-11e5-8684-423fa7dbfa5c.jpg)

**Comment by vanderbeam** [comment]
Augh why are stock photos so terrible. 

![11](https://cloud.githubusercontent.com/assets/12962001/10657887/4ca422b0-7846-11e5-9380-43cff5bd8542.png)
This one is the closest one to working but you can't really see much with the watermark there. The rest to work because the hero is only about 400px high. 
I'll look through some more photos. Or if having a note pad show up in the photo below is the only this keeping us from choosing the other one, replacing the photo below is also an option.

**Comment by rodneystrong** [comment]
Try one with the one you found that I like and take a screenshot as well please.

**Comment by rodneystrong** [comment]
This one: http://depositphotos.com/4755399/stock-photo-female-college-students-in-a.html

**Comment by vanderbeam** [comment]
![12](https://cloud.githubusercontent.com/assets/12962001/10658572/1b6211e2-784d-11e5-8567-68261244c996.png)

This is at 50% 25%

**Comment by rodneystrong** [comment]
I like it. Please add it to the gh-pages branch and push it for @irms to view live

**Comment by vanderbeam** [comment]
@irms The hero is live, awaiting your approval :)
http://editllc.github.io/client-codergirlz/index.html

**Comment by irms** [comment]
@vanderbeam lets go with it for now and see what the client says.

**Comment by rodneystrong** [comment]
@irms  ***poke poke***    when do you think you'll hear from client?

**Comment by irms** [comment]
@aleeex Just sent a tickler yesterday.

**Comment by rodneystrong** [comment]
thaaaank you miss

**Comment by irms** [comment]
Client has approved your image!

**Comment by irms** [comment]
They'll send feedback over time, but this project is 95% complete. Please invoice.

**Comment by rodneystrong** [comment]
@irms excellent, thank you for the update. 

@vanderbeam please email me or Irma the invoice. If you email irma, please CC so I know she got it. 

Well done by the way!
