### ISSUE TITLE
Changes from client 11232015

### ISSUE THREAD

**Issue by irms** [EditLLC/client-codergirlz#13]
The site looks great and we would like to launch it soon. The only thing missing is Edison High School on the “Chapters” page. Other than that, we are ready to get the HTML code.

**Comment by irms** [comment]
That was extracted from an email from the client. Sorry if that wasn't clear.

**Comment by vanderbeam** [comment]
How about all the lorem in the chapters area? I assume they'll want that replaced with something before launch.

**Comment by vanderbeam** [comment]
(done)

**Comment by irms** [comment]
I have no idea! I'll check.

**Comment by rodneystrong** [comment]
Just wanted to follow up about this. Any word from the client?

**Comment by rodneystrong** [comment]
Sorry, forgot to ping your name @irms

**Comment by irms** [comment]
Yes. Loved it.

This project is delivered and invoiced.

**Comment by vanderbeam** [comment]
@irms Nothing about the Chapters content?

**Comment by irms** [comment]
@vanderbeam not a word.

**Comment by rodneystrong** [comment]
good enough for me. any new changes that come up will merit a new issue. good job @vanderbeam
