### ISSUE TITLE
Anchor Links

### ISSUE THREAD

**Issue by vanderbeam** [EditLLC/client-codergirlz#3]
Everything is done except the anchor links aren't working. None of them. Which is silly; I've done these a million times. But the Chapters Index links will only go down to the top of the chapter's container. Even sillier, I added a "Back to top" feature since the list got kinda lengthy and not only does it NOT take you back to the top, but it consider each chapter container as "the top" and if you continue to click the "Top" button it will descend the list.

I know I'm overlooking something but I'm at a loss as to what it is. 

http://editllc.github.io/client-codergirlz/chapter.html

**Comment by vanderbeam** [comment]
I also just noticed the Title for this page is wrong. It will be correct in the next push.

**Comment by vanderbeam** [comment]
I fixed the "Top" link which is silly because it's exactly how I've set up the rest of the anchor BUT THEY DON'T WORK!

**Comment by rodneystrong** [comment]
I'll look into this. 

By the way, can you please fix the broken image links on this page?

**Comment by vanderbeam** [comment]
Broken image links?

**Comment by rodneystrong** [comment]
Yes, these are broken image links and I see them all over the page:

![screen shot 2015-09-29 at 1 59 18 am](https://cloud.githubusercontent.com/assets/539962/10159565/e285d414-664d-11e5-8134-6aad444862b5.png)

Please link to them correctly so that they actually display on the page. 

I'll create a separate issue for you on this.

**Comment by vanderbeam** [comment]
Oh weird. They show up for me fine in the local but not the gh-pages. I'll look into this issue.

**Comment by rodneystrong** [comment]
*nods 
Thanks.
Please remember to double-check your work; I have made this mistake plenty of times as well.

**Comment by vanderbeam** [comment]
This issue is driving me absolutely bonkers! If you paste the exact same code into a CodePen or a JSFiddle, it work perfectly.

**Comment by irms** [comment]
the chapters page is looking so much better.

@vanderbeam: are you optimizing your images for the web (both filesize and
image size)?

**Comment by vanderbeam** [comment]
@irms I saved for web, but I'm honestly not sure if that optimized it. I'm afraid I'm lacking in knowledge of this subject.

**Comment by irms** [comment]
@aleeex to the rescue?

**Comment by rodneystrong** [comment]
@irms Yea, I created an issue for this yesterday here: #4 

@vanderbeam  upload 3 of the original school images (the PNG format) to our buildicus google drive (I made a 'coder girlz' folder) and upload the same ones that you optimized (the JPG format) as well so I can do a comparison.

**Comment by vanderbeam** [comment]
@rodneystrong I dropped three different school sets.

**Comment by rodneystrong** [comment]
@irms she did well optimizing the images through photoshop, however there's a larger problem. 

There are 17 iframes on the page; google maps iframes no less. According to the 'network' tab of the dev tools, each iframe adds at least 1.02 seconds to the page load, times 17 means at least 17 seconds of waiting not to mention the resource drain on the clients browser given the nature of iframes. 

I believe this is something we won't be able to circumvent. 

If it's any consolation, you'll be able to present this information to the client if the question of load speed comes up. Maybe we can offer the option of screenshotting each map and placing it as an image for each school with the understanding that the user will lose any interactivity (zoom, pan, write a review, etc) that the iframe offers.

@vanderbeam good job on the images. i'm still working on the anchor links in this issue.

**Comment by irms** [comment]
@aleeex. Very good point!

I would prefer to screen shot and link off to the actual map.

**Comment by vanderbeam** [comment]
I'm on it!

**Comment by irms** [comment]
Thanks, @vanderbeam!

**Comment by vanderbeam** [comment]
@irms @rodneystrong They're uploaded. I tried to get the screen shots to get crossroads.

**Comment by irms** [comment]
​@vanderbeam good work! So. Much. Faster.​

**Comment by rodneystrong** [comment]
Good stuff on getting that up quickly. 

I figured out the anchor link issue. For some reason my mic isn't working correctly on my Mac, so I'll post a video for what you need to do when I get to my PC.

**Comment by rodneystrong** [comment]
@vanderbeam here's the video that explains what happened and what you can fix in your code:
http://somup.com/co6VDjbwq

I also just did a minor push so that you at least have some sample code to go off of. Be sure to **PULL** the latest code from github before you start.

**Comment by vanderbeam** [comment]
I pushed it with some margins on the top so you can see there is a title but not enough of a margin where each one just has a bunch of white space. Let me know if you want more space. All the anchors work! That you so much and I will keep this in mind for the future.

**Comment by rodneystrong** [comment]
Well done; I've double-checked your fix. 

I went in and added a margin-top: 30px to the .chapters. It's more spacing but it's not an over-the-top amount and also aligns perfectly when users click a bookmark anchor link.
