### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-codergirlz#4]
http://editllc.github.io/client-codergirlz/chapter.html

Please fix them. 

Also, I notced they are all PNG files; this significantly increases the file size of the image. 

Please take whatever PNG's they gave you and convert them to JPG using the "Save file for web" option in photoshop.

due:
9-29-15   5p

**Comment by vanderbeam** [comment]
Fixed. Apparently github is case sensitive... who knew!

**Comment by vanderbeam** [comment]
OK this is fixed. I think the background make the banners look much nicer, yeah?

**Comment by rodneystrong** [comment]
I concur; good work
