### ISSUE TITLE
Bullet size

### ISSUE THREAD

**Issue by irms** [EditLLC/client-codergirlz#5]
Now that the font is larger, the bullets seem miniature. Any way to make them the same size, or remove them? They're also higher than the text itself.

https://www.dropbox.com/s/k3a6r64kni26j8y/Screenshot%202015-10-01%2017.49.28.png?dl=0

due:
10-5-15    10p

**Comment by vanderbeam** [comment]
Them being higher than the text is an issue I tried to fix and didn't succeed. I'll try to take another whack at them. In the mean time I'll make them bigger.

**Comment by rodneystrong** [comment]
@vanderbeam these aren't font-icons, so you're going to want to go back to where you found these images and see if they have a 20 x 20 or  recreate them in illustrator. 

@AaronAguilar is really good at tracing and converting objects into vector for pixel output.

**Comment by vanderbeam** [comment]
@rodneystrong I made these. I have the vectors. I still can't figure out how to put them inline quite yet though.

**Comment by rodneystrong** [comment]
ok, export an 18 x 18 and a 20 x 20 for me and upload them here AND to the google drive. I will work on positioning

**Comment by vanderbeam** [comment]
![20x20](https://cloud.githubusercontent.com/assets/12962001/10242004/62d564c6-68a2-11e5-9a7b-fec49b6fd22d.png)
![18x18](https://cloud.githubusercontent.com/assets/12962001/10242005/62e9e20c-68a2-11e5-8949-12cf7c3c6b01.png)
@rodneystrong

**Comment by vanderbeam** [comment]
Resending the 18x18 so it's not cut off 
![18x18](https://cloud.githubusercontent.com/assets/12962001/10242031/98681f52-68a2-11e5-980b-ef704f19e3b2.png)

**Comment by rodneystrong** [comment]
Excellent, thank you miss. reassigning to me.
