### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by irms** [EditLLC/client-codergirlz#8]
So, I did a little market research.... people don't like the semicolons :(

I thought they were cleaver, but it kills the readability.

<img width="274" alt="screenshot 2015-10-01 17 53 46" src="https://cloud.githubusercontent.com/assets/643997/10237377/7dfba496-6865-11e5-8423-323d8cc948e3.png">

due:
10-3-15   4p

**Comment by rodneystrong** [comment]
really now.. interesting. luckily it'll be an easy fix for @vanderbeam

**Comment by vanderbeam** [comment]
On it!

**Comment by vanderbeam** [comment]
This is done.

**Comment by rodneystrong** [comment]
good work lady
