### ISSUE TITLE
CTA Bar

### ISSUE THREAD

**Issue by irms** [EditLLC/client-codergirlz#9]
Can we add a Call to Action bar underneath the hero image?

H2: "Interested in learning to code?"
Button "Let us know!"

Takes them to the interest form.

![codergirlz cta](https://cloud.githubusercontent.com/assets/643997/10237433/3b956406-6866-11e5-828c-384c8394b69c.png)

Please?

due:
10-2-15   8p

**Comment by rodneystrong** [comment]
Excellent suggestion @irms 

@vanderbeam please implement it in the way the green bar looks on http://www.lavoguebeautyshoppe.com/. Specifically I'm referring to the green bar that says "Call today for an appointment" 

The CTA bar will be right up against the the hero image you have, so remove the drop shadow that's currently at the bottom of the hero image and place it under the new bar. Make the color of the bar the same pink that's on the site and the color of the button itself the darkest teal you're already using on the site. The text color of the button should be #fff. If the teal clashes too much with the pink then try a darker shade of the pink (10% darker) for the button color.

**Comment by rodneystrong** [comment]
@irms I changed your H1 to an H2 for semantic purposes. There is already an H1 on the page.

**Comment by vanderbeam** [comment]
I'm going to drop it down to h3. The second "why code" is an h2 and I think that'd be too big and overpowering.

**Comment by vanderbeam** [comment]
I'm not sure what you wanted it to say but is this the design you had in mind? http://editllc.github.io/client-codergirlz/

**Comment by irms** [comment]
Yes, but see the text I am after in the original issue. Plus, add button.

**Comment by vanderbeam** [comment]
@irms http://editllc.github.io/client-codergirlz/
Let me know what you think of the button. I asked a "youngster" (she's in the demographic) what she thought and the button styling was based on her suggestions.

**Comment by irms** [comment]
Well, to be really honest, I think a normal button the same greenish color
in the very, very top left would be good.

**Comment by vanderbeam** [comment]
very top left of the whole page?

**Comment by irms** [comment]
Right, #3FB8AF.

**Comment by vanderbeam** [comment]
Do you want me to take out the CTA bar since the button would be separate from it then?

**Comment by irms** [comment]
...no, i'm just saying make the button color the same as that green color in the top left of the page.

**Comment by vanderbeam** [comment]
@irms Sorry for the misunderstanding, is this what you had in mind? http://editllc.github.io/client-codergirlz/

**Comment by irms** [comment]
@vanderbeam! Yes! Just make the button smaller and look more like...a
button? (small shadow or border maybe?)

**Comment by vanderbeam** [comment]
@irms Closer? http://editllc.github.io/client-codergirlz/

**Comment by irms** [comment]
Haha! It's a bit much. Try this:

```
.btn-cta { 
  color: #FFFFFF; 
  background-color: #3FB8AF; 
  border-color: #31968F; 
} 
 
.btn-cta:hover, 
.btn-cta:focus, 
.btn-cta:active, 
.btn-cta.active, 
.open .dropdown-toggle.btn-cta { 
  color: #FFFFFF; 
  background-color: #37A8A0; 
  border-color: #31968F; 
} 
 
.btn-cta:active, 
.btn-cta.active, 
.open .dropdown-toggle.btn-cta { 
  background-image: none; 
} 
 
.btn-cta.disabled, 
.btn-cta[disabled], 
fieldset[disabled] .btn-cta, 
.btn-cta.disabled:hover, 
.btn-cta[disabled]:hover, 
fieldset[disabled] .btn-cta:hover, 
.btn-cta.disabled:focus, 
.btn-cta[disabled]:focus, 
fieldset[disabled] .btn-cta:focus, 
.btn-cta.disabled:active, 
.btn-cta[disabled]:active, 
fieldset[disabled] .btn-cta:active, 
.btn-cta.disabled.active, 
.btn-cta[disabled].active, 
fieldset[disabled] .btn-cta.active { 
  background-color: #3FB8AF; 
  border-color: #31968F; 
} 
 
.btn-cta .badge { 
  color: #3FB8AF; 
  background-color: #FFFFFF; 
}
```

Then of course, give the button a .btn-cta class.

**Comment by vanderbeam** [comment]
http://editllc.github.io/client-codergirlz/

Ha, it's an ittie bittie button! :D
Did you intend it to be that small or do you want me to bump it up to a 14pt/16pt? 
Thought I'd ask beforehand.

**Comment by irms** [comment]
Uh, oh. that's too fuckin' itty-bitty! (ref:
https://www.youtube.com/watch?v=Fhuh-wGy5ic)

Will you please fix my nonsense?

**Comment by vanderbeam** [comment]
@irms 
Upped to 18pt
increased the border radius so the button sides stayed round
http://editllc.github.io/client-codergirlz/

Let me know if it's still too fuckin' itty-bitty. 
If I didn't get it this time I may be hosting my own pool dinner party for myself! Haha.

**Comment by irms** [comment]
HAHA!! That's perfect. Good work.

**Comment by rodneystrong** [comment]
@vanderbeam great job all around. i made a video of a few items I changed/polished up. It explains why I made those changes and hopefully it helps you with future projects. Here: http://screencast-o-matic.com/watch/co6IVphcvh

@irms how did the meeting with the client go? what would they like use to change?

**Comment by irms** [comment]
@aleeex, so far nothing. They really like it. They're sending the site to
some middle schools to get feedback there!

**Comment by rodneystrong** [comment]
@irms  wooord
